# Generated by Django 4.0.4 on 2022-04-27 09:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_rename_id_order_order_number_alter_order_user_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'delivery_companies',
            },
        ),
        migrations.RemoveField(
            model_name='ordershipment',
            name='company',
        ),
        migrations.AddField(
            model_name='ordershipment',
            name='delivery_company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='payments.deliverycompany'),
        ),
    ]
