# Generated by Django 4.0.4 on 2022-04-27 09:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_deliverycompany_remove_ordershipment_company_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordershipment',
            name='delivery_company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payments.deliverycompany'),
        ),
    ]
