# Generated by Django 4.0.4 on 2022-05-01 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0006_rename_deliverycompany_carrier_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='check_box',
            field=models.BooleanField(default=True),
        ),
    ]
