# Generated by Django 4.0.4 on 2022-04-26 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=10)),
                ('email', models.CharField(max_length=50, unique=True)),
                ('password', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=200)),
                ('phone_number', models.CharField(max_length=200)),
                ('gender', models.IntegerField(choices=[(1, 'Male'), (2, 'Female')])),
                ('age', models.IntegerField(choices=[(10, 'Teenage'), (20, 'Twenties'), (30, 'Thirties'), (40, 'Forties')], null=True)),
            ],
            options={
                'db_table': 'users',
            },
        ),
    ]
