# Generated by Django 4.0.4 on 2022-04-27 07:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_address_alter_user_age_alter_user_gender_and_more'),
        ('products', '0003_caution_alter_product_price_alter_product_sale_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'product_statuses',
            },
        ),
        migrations.RenameField(
            model_name='product',
            old_name='sale',
            new_name='discount',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='stars',
            new_name='rating',
        ),
        migrations.AlterField(
            model_name='review',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product'),
        ),
        migrations.AlterField(
            model_name='review',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.user'),
        ),
        migrations.AlterField(
            model_name='sizestock',
            name='size',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='products.size'),
        ),
        migrations.AddField(
            model_name='product',
            name='product_status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.productstatus'),
        ),
    ]
