# Generated by Django 4.0.4 on 2022-04-28 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_productstatus_rename_sale_product_discount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='size',
            name='size',
            field=models.CharField(max_length=10),
        ),
    ]
