# Generated by Django 4.0.4 on 2022-04-30 07:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_size_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='review',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='products.review'),
        ),
    ]
